// <auto-generated />
using FireboxTrucks.Web.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FireboxTrucks.Web.Migrations
{
    [DbContext(typeof(FireboxTrucksContext))]
    [Migration("20220413013210_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("FireboxTrucks.Web.Models.Caminhao", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AnoFabricacao")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<int>("AnoModelo")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<int>("ModeloID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ModeloID");

                    b.ToTable("Caminhao");
                });

            modelBuilder.Entity("FireboxTrucks.Web.Models.Modelo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Modelo");
                });

            modelBuilder.Entity("FireboxTrucks.Web.Models.Caminhao", b =>
                {
                    b.HasOne("FireboxTrucks.Web.Models.Modelo", "Modelo")
                        .WithMany()
                        .HasForeignKey("ModeloID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modelo");
                });
#pragma warning restore 612, 618
        }
    }
}
